main: com.kzics.dbzuhc.DbzUHC
version: 1.0.0
name: DbzUhc
commands:
  dbzuhc:
    description: Main command for the plugin
    usage: /dbzuhc
    aliases: [uhc]
    permission: dbzuhc.command
    permission-message: You don't have permission to use this command